### ISSUE TITLE
Pop!_OS 22.04 - 6.16.3-76061603-generic

### ISSUE THREAD

**Issue by robertstrom** [bytium/vm-host-modules#20]
I just updated my Pop!_OS 22.04 today and VMware Workstation will not launch and I am getting errors when trying to compile the kernel modules.

**uname -a**
```
Linux oryx-pro 6.16.3-76061603-generic #202508231538~1758010842~22.04~85d2e57 SMP PREEMPT_DYNAMIC Tue S x86_64 x86_64 x86_64 GNU/Linux
```

- error message seen when trying to compile the kernel modules
```
┌─(/mnt/Data/vm-host-modules)────────────────────────────────────────────────────────────────────────────────────────────────────────────(rstrom@oryx-pro:pts/0)─┐
└─(16:33:09 on 17.6.2)──> make                                                                                                                     ──(Mon,Sep22)─┘
make -C vmmon-only 
make[1]: Entering directory '/mnt/Data/vm-host-modules/vmmon-only'
Using kernel build system.
make -C /lib/modules/6.16.3-76061603-generic/build/include/.. M=$PWD SRCROOT=$PWD/. \
  MODULEBUILDDIR= modules
make[2]: Entering directory '/usr/src/linux-headers-6.16.3-76061603-generic'
make[3]: Entering directory '/mnt/Data/vm-host-modules/vmmon-only'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: x86_64-linux-gnu-gcc-12 (Ubuntu 12.3.0-1ubuntu1~22.04.2) 12.3.0
  You are using:           gcc-12 (Ubuntu 12.3.0-1ubuntu1~22.04.2) 12.3.0
  CC [M]  linux/driver.o
linux/driver.c:21:10: fatal error: driver-config.h: No such file or directory
   21 | #include "driver-config.h"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[5]: *** [/usr/src/linux-headers-6.16.3-76061603-generic/scripts/Makefile.build:287: linux/driver.o] Error 1
make[4]: *** [/usr/src/linux-headers-6.16.3-76061603-generic/Makefile:2010: .] Error 2
make[3]: *** [/usr/src/linux-headers-6.16.3-76061603-generic/Makefile:248: __sub-make] Error 2
make[3]: Leaving directory '/mnt/Data/vm-host-modules/vmmon-only'
make[2]: *** [Makefile:248: __sub-make] Error 2
make[2]: Leaving directory '/usr/src/linux-headers-6.16.3-76061603-generic'
make[1]: *** [Makefile:121: vmmon.ko] Error 2
make[1]: Leaving directory '/mnt/Data/vm-host-modules/vmmon-only'
make: *** [Makefile:24: vmmon-only] Error 2
```

I will keep looking but would also really appreciate anyone who knows how to fix this chiming in here.

Thanks!

**Comment by Hackerobi** [comment]
I got something similar. 
`uname -a `

`Linux pop-os 6.16.3-76061603-generic #202508231538~1758561135~22.04~171c8de SMP PREEMPT_DYNAMIC Mon S x86_64 x86_64 x86_64 GNU/Linux`


Output when compiling:
`obi1@pop-os:~/Downloads/vmware-host-modules$ make
*-----------------------------------------------------------------------------
* Branch workstation-16.2.0 has been retired on 2022-04-04 and has not been
* receiving any updates since. Please switch to latest 16.x version
* available.
*
* Latest kernel version this branch is intended to work with is 5.17.
*-----------------------------------------------------------------------------
make -C vmmon-only 
make[1]: Entering directory '/home/obi1/Downloads/vmware-host-modules/vmmon-only'
Using kernel build system.
make -C /lib/modules/6.16.3-76061603-generic/build/include/.. M=$PWD SRCROOT=$PWD/. \
  MODULEBUILDDIR= modules
make[2]: Entering directory '/usr/src/linux-headers-6.16.3-76061603-generic'
make[3]: Entering directory '/home/obi1/Downloads/vmware-host-modules/vmmon-only'
  CC [M]  linux/driver.o
linux/driver.c:20:10: fatal error: driver-config.h: No such file or directory
   20 | #include "driver-config.h"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[5]: *** [/usr/src/linux-headers-6.16.3-76061603-generic/scripts/Makefile.build:287: linux/driver.o] Error 1
make[4]: *** [/usr/src/linux-headers-6.16.3-76061603-generic/Makefile:2010: .] Error 2
make[3]: *** [/usr/src/linux-headers-6.16.3-76061603-generic/Makefile:248: __sub-make] Error 2
make[3]: Leaving directory '/home/obi1/Downloads/vmware-host-modules/vmmon-only'
make[2]: *** [Makefile:248: __sub-make] Error 2
make[2]: Leaving directory '/usr/src/linux-headers-6.16.3-76061603-generic'
make[1]: *** [Makefile:117: vmmon.ko] Error 2
make[1]: Leaving directory '/home/obi1/Downloads/vmware-host-modules/vmmon-only'
make: *** [Makefile:21: vmmon-only] Error 2`
